# Generated by Django 3.2.3 on 2021-06-03 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_newscategory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newscategory',
            options={'verbose_name': 'категории новостей', 'verbose_name_plural': 'категории новостей'},
        ),
    ]
